title: Documentation WHMCS / Bexio Integration
description: by AlpineLink

url: "https://alpinelink.github.io"
baseurl: "/whmcs-bexio-docs"

color_scheme: dark

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
