title: Documentation WHMCS / Bexio Integration
description: by AlpineLink

url: "https://docs.bexio-whmcs.ch"
baseurl: "/index.md"

color_scheme: dark

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
